### ISSUE TITLE
Tests non fonctionnels

### ISSUE THREAD

**Issue by cspaier** [cspaier/pydiderotlibs#10]
## test_stats_proba
```
print("Un nombre au hasard dans la liste précédente : ", choix(contenu))
NameError: name 'contenu' is not defined
```

## test_listes
```
filin = open(fichier, 'r')
FileNotFoundError: [Errno 2] No such file or directory: 'TableurPourTest.csv'
```

## test couleurs
```
root = Tk()
TypeError: 'module' object is not callable
```

**Comment by al-coloic** [comment]
bug 1 et 3 fixed

je regarde le 2

**Comment by al-coloic** [comment]
j'ai commenté directtement dans le fichier : l'appel de la fonction demande des fichiers qui sont dans le répertoires exemples du dépôt guit mais absent du pip.
Inutil de les ajoutezr dans le pip, vu que la fonction ne sert qu'au dev
