### ISSUE TITLE
import math_lycee dans graphique

### ISSUE THREAD

**Issue by cspaier** [cspaier/pydiderotlibs#16]
Pouquoi?

https://github.com/cspaier/pydiderotlibs/blob/e8678b773b8ce73e55f46cadf75a1d44453e9855/pydiderotlibs/graphique.py#L13

**Comment by cspaier** [comment]
De plus ca donne un conflit avec `vecteur`.

Globalement, je suggère de n'importer que les libs utilisées.

**Comment by byache** [comment]
C'est pas bien ?
C'est pour avoir la commande aléa() (et éventuellement d'autres) sans faire plusieurs import.
Mais bon, moi finalement je leur fait utiliser randint() (puisqu'on programme en anglais :-)

**Comment by cspaier** [comment]
> C'est pas bien ?

Comme je disais, ça fait un conflit entre `math.lycee.vecteur` et `graphique.vecteur`.

Notons qu'il est globalement déconseillé d'utiliser les imports `from truc import *`.

On lit [ici](https://www.python.org/dev/peps/pep-0008/#imports):

> Wildcard imports (from <module> import *) should be avoided, as they make it unclear which names are present in the namespace, confusing both readers and many automated tools. There is one defensible use case for a wildcard import, which is to republish an internal interface as part of a public API (for example, overwriting a pure Python implementation of an interface with the definitions from an optional accelerator module and exactly which definitions will be overwritten isn't known in advance)

Je pense que c'est une meilleure pratique de n'importer que le nécessaire au fonctionnement de la librairie. 
Il semble plus simple et sain d'avoir une librairie faisant une chose et le faisant bien. Si l'utilisateur veut utiliser des outils de deux librairies, il peut importer les deux.
