### ISSUE TITLE
Idée: lien vers doc à l'import

### ISSUE THREAD

**Issue by cspaier** [cspaier/pydiderotlibs#17]
Au début de nos modules, on pourrait rajouter une  instruction du genre:
```print("Merci d'utiliser la librairie machin du module pydiderot.\nN'hésitez pas à consulter la documentation en ligne:\nhttps://pydiderotlibs.readthedocs.io/")```
. Comme ca, ca affichera le lien vers la doc à l'import.

J'ai testé et les liens sont cliquables dans la console thonny: 
![image](https://user-images.githubusercontent.com/44053087/68698266-decab200-0580-11ea-990d-59d7670f66cd.png)

**Comment by byache** [comment]
Ah oui, super. (Il faut faire gaffe de garder la doc bien jour :-)

**Comment by cspaier** [comment]
> Il faut faire gaffe de garder la doc bien jour

On est pas mal franchement. L'avantage d'autodoc c'est que c'est automatique à partir des docstrings.

Perso j'invite les élèves à consulter la doc en ligne, et ca fonctionne! Ca reste le meilleur outil du codeur.

**Comment by cspaier** [comment]
J'en ai profité pour cacher le message de pygame.

**Comment by byache** [comment]
Avec les secondes, j'utilise aussi ce doc (qui n'est pas bien terminé et que j'ai mis en version odt + pdf dans 'static').
Je ne leur laisse pas, j'en ai une vingtaine dans on sac et je le leur prête dès que c'est utile.
https://github.com/cspaier/pydiderotlibs/blob/master/docs/source/_static/Liste%20instructions%20python%20bibliotheque%20graphique-py.pdf

**Comment by cspaier** [comment]
Pourquoi pas?

Si c'était moi, j'écrirai ca en markdown comme ça on l'aurait en ligne et en pdf automatiquement.

Bon perso je trouve que la doc est simple à utilisée et représente une bonne pratique globalement.

Dans tout les cas, l'issue est résolue? on peut fermer?
