### ISSUE TITLE
Utilisation de la fonction eval() dans liste.CSV2liste

### ISSUE THREAD

**Issue by cspaier** [cspaier/pydiderotlibs#18]
C'est pas une pratique recommandée. On fait quoi en fait la?

https://github.com/cspaier/pydiderotlibs/blob/f03abf4a1e0942447c2d5a639cf52b8f3816dae7/pydiderotlibs/listes.py#L13-L46

**Comment by al-coloic** [comment]
ben on prend un ficheir CSV et on en tire une liste.
Si l'argument est une lettre, on transforme la colonne en liste
Si l'argument est un nombre, on transforme la ligne en liste.
mais il faut réécrire cette fonction. Et la commenter !

**Comment by cspaier** [comment]
Oui, mais ma question c'est: Pouquoi on utiliser `eval()`?
Parceque c'est (très) mal d'utiliser `eval()`, surtout sur une entrée utilisateur!
Pour être clair, on lit [ici](https://docs.python.org/fr/3/library/functions.html#eval):

> L'argument expression est analysé et évalué comme une expression Python

Donc on va executer le contenu du csv comme du code python. Quand je disais "C'est pas une pratique recommandée." c'était un euphémisme.

Dans tout les cas il faut réécrire oui. Je vote pour deux fonctions `csv_ligne` et `csv_colonne` afin de pouvoir typer les entrés.

Sinon, c'est vraiment utile comme fonction?

**Comment by al-coloic** [comment]
1. ça vient du projet edupython : cela explique beaucoup de choses !
2. la fonction me paraît utile pour travailler sur un tableau de données (tous niveaux) et son traitement statistique.
3. Je la gardais car pas eu le temps de la réécrire : ta proposition csv_ligne ou cvs_colonne me paraît mieux (sémantiquement et donc pédagogiquement/dicdactiquement, pan dans les dents)
4. on connaît les euphémisme chez les joueurs de go, pas besoin de préciser.

**Comment by al-coloic** [comment]
et je crois que le eval est pour transformer un string du CSV en str direct.

**Comment by cspaier** [comment]
>  transformer un string du CSV en str direct
C'est ce que je craignais: on utilise `eval()` pour convertir un `str` en `str`!

Du coup c'est clair:
1) on garde la fonction.
2) on s'abstient de se défouler sur edupython même si c'est tentant. Éventuellement on ouvre un truc chez eux pour mentionner le problème un jour.
3) on réécrit à l'occasion en deux fonctions `csv_ligne` et `csv_colonne`.

> on connaît les euphémisme chez les joueurs de go, pas besoin de préciser.

Quand ton prof te dit "c'est un coup plutôt rare"...

**Comment by al-coloic** [comment]
fait

**Comment by al-coloic** [comment]
l'export en libre office sous CSV de nombres à virgules mets des virgules partout et traite les nombres comme des str.

a corriger

**Comment by cspaier** [comment]
On utilise plus `eval` en tout cas.
