### ISSUE TITLE
Option autorefresh dans graphique

### ISSUE THREAD

**Issue by cspaier** [cspaier/pydiderotlibs#19]
Des élèves commencent à avoir une utilisation sérieuse de la librairie graphique.

Notre approche a été jusqu'ici d’appeler `pygame.display.update()` à chaque création d'objet.

Ca n'est clairement pas optimisé, ralenti l'affichage et peut donner lieu a des scintillements.

Je propose la modification suivante:
- rajouter un argument optionnel `autorefresh` dans `fenetre()` par défaut à `True`.
- Initialiser une variable globale `_autorefresh` dans `fenetre()`.
- créer une fonction `rafraichir()` qui appelle `pygame.display.update()`.
- dans chaque fonction qui modifie l'affichage, on appelle `pygame.display.update()` uniquement si `_autorefresh` vaut `True`.

Points positifs:
- Compatible avec l'utilisation actuelle.
- Utilisation optimisée facile:
```python
fenetre(autorefresh=False)
point(x, y)
rectangle(x, y)
rafraichir()
```
- facile à mettre en œuvre de notre coté.

Point négatif:
- Encore une variable globale: voir #15 et #7

**Comment by byache** [comment]
Je souscris... De toute façon, j'aime les variables globales :-)

**Comment by cspaier** [comment]
Et [documenté](https://pydiderotlibs.readthedocs.io/librairies/graphique.html#rafraichissement-automatique) ;)
