### ISSUE TITLE
pydiderot ?

### ISSUE THREAD

**Issue by byache** [cspaier/pydiderotlibs#23]
Il faudrait se préoccuper de pydiderot / pydiderotlibs.
1) On peut mentionner dans l'index de pydiderot que tout se passe maintenant dans pydiderotlibs ?
(ou alors on supprime carrément les librairies de pydiderot, pour éviter les ambiguïtés pour qqn qui forkerait pydiderot au lieu de pydiderotlibs ?)
2) Dans la doc, il y a un dossier "formation". On le laisse dans pydiderot ou on le copie dans pydiderotlibs ?
3) On crée un autre dossier "activités" avec une progression et des exemples d'activités ? (des trucs qu'on a testé et qu'on pet recommander aux collègues)

**Comment by cspaier** [comment]
Salut Paul!

Oui la question est légitime et a été posée [ici](https://github.com/cspaier/pydiderot/issues/34).

1. En l'état c'est un peu le bazar. Pydiderot, c'est juste thonny + pydiderotlibs. Je suis toujours pas certain de la pertinence de distribuer ca. Si on le garde, il faut mettre à jour la doc effectivement.

2.  Je suis pour mettre le dossier "formation" dans un dépôt dédié. Ca n'a pas ca place dans pydiderotlibs je pense.

3. Du coup, on pourrait avoir un dépôt "Pédagogie" contenant  les docs formations et des activités?

J'aime bien que pydiderotlibs soit juste un dépôt de librairies python dédiées à l'enseignement. Un objectif simple et clair c'est bon.

Que chaque dépôt ait un objectif clair et définit en fait.

**Comment by byache** [comment]
Oui, d'accord avec ce que tu proposes. On peut ouvrir un nouveau dépôt "pythonlycee" (ou autre, mais plus parlant que "pedagogie") mais il ne contiendrait que de la doc. Du coup, ce serait plutôt un petit site web. C'est peut-être un peu bizarre de mettre ça sur github... En même temps, c'est toujours le même problème. L'éducation nationale ne propose pas ce genre d'hébergement et refusera que ce soit hébergé sur un site officiel. Et github est pratique pour collaborer à plusieurs ?

**Comment by cspaier** [comment]
Bon, j'ai mis à jour pydiderot et la doc:

> Ce projet fournit un environnement de développement Python portable correspondant à celui utilisé par les élèves et les professeurs du lycée Denis Diderot à Marseille.

J'ai retiré la doc des bibliothèques pydiderotlibs.

Pour l'instant j'ai gardé formation. Il reste donc un peu de ménage à faire.

**Comment by al-coloic** [comment]
Je relance le fil par exemple sur [https://pydiderotlibs.readthedocs.io/librairies/repere.html](https://pydiderotlibs.readthedocs.io/librairies/repere.html) le lien qui pointe vers le code de repere est mort.

De ce que je comprends, on a 3 oeuvres en cours
- pydiderotlibs : pour faire de la programmation en mode élève
- pydiderot : pour avoir un ide 'sympa' + les libs pour pouvoir travailler au lycée
- un truc encore mal nommé : la partie professeur

je veux bien bosser un peu la doc, je crois qu'il y a besoin et le code des librairies si mais j'attends de voir si j'ai bien compris.

**Comment by cspaier** [comment]
Bien vu pour la correction. Globalement, la doc a toujours besoin d'un peu de relecture et corrections.

Sinon oui, on a 3 œuvres:

- pydiderolibs: Des librairies python facilitant l'enseignement de python dans le secondaire
- pydiderot: Un ide simple et adapté à l'enseignement avec nos librairies préinstallés. Le tout fournis dans un fichier zip portable.
- pyprof?:  De la doc pour les profs. A séparer dans un dépôt dédier. Autres idées de nom?

> je veux bien bosser un peu la doc, je crois qu'il y a besoin et le code des librairies si mais j'attends de voir si j'ai bien compris.

Tout travail est plus que bienvenu.

De mon côté, je vais créer un dépôt `pyprof` contenant la doc enseignante. Une fois qu'on a bien nommé et séparé chaque projet, on ferme cette issue?

**Comment by al-coloic** [comment]
pyprof_lycee ?
Ca sera un peu le début de ton idéee de mutu des ressources péda sur github...

**Comment by al-coloic** [comment]
on ferme ? A part le choix du nom du volet pédagogie je vois pas.
pydago ?

**Comment by cspaier** [comment]
Je vote pydago. Qui ne dit mot consent. On ferme.

**Comment by cspaier** [comment]
Done: https://github.com/cspaier/pydago

**Comment by cspaier** [comment]
Après réflexion, je me suis dit qu'il n'était pas pertinent d'avoir les dépôts hébergé sur mon github.
De plus, Pydiderot est plus le projet général alors que https://github.com/cspaier/pydiderot est en fait un IDE.

Du coup, j'ai créé une organisation nommée [Pydiderot](https://github.com/Pydiderot). @byache et @al-coloic je vous ait ajouté comme membres de l'orga.

L'idée est d'unifier les 3 projets sous le nom de Pydiderot:
- PydiderotIDE: anciennement Pydiderot. Une version portable pour windows de Thonny + pydiderotlibs.
- Pydiderotlibs
- Pydago: Formation profs

Et un jour, peut-être Pydactivites(?) ou pymutu(?) pour mutualisation d'activités?

Si ça vous va, je vais transférer les dépôts à l'organisation Pydiderot et renomer Pydiderot en PydiderotIDE. Ca va changer les urls de https://github.com/cspaier/pydiderotlibs à https://github.com/pydiderot/pydiderotlibs. Il faudra mettre un peu à jour la doc du coup.

On pourra éventuellement unifier un peu la doc (à voir et discuter).

Je ré ouvre et attends vos avis.

**Comment by al-coloic** [comment]
> Il faudra mettre un peu à jour la doc du coup.

rascal !

On peut dire oui à tout. Mais ça se voit que tu bosses à l'EN, vieille relique du pcf... et la fédération dude ! Rien ne nous obligeait à regrouper.
Enfin bref, le fantôme de Robert Hue hante ce github, je me méfierai à l'avenir.

Mais fais la bascule pendant les vacances stp, je fais une "formation" aux profs jeudi, autant avoir une doc à jour.

**Comment by cspaier** [comment]
Rho! Je ne réponds pas aux vilenies mais j'argumente, quitte à m'enfoncer.

Les 3 projets existant sont clairement liés par un projet commun: le travail des enseignants du lycée Diderot pour faciliter l'enseignement de Python. Les regrouper n'est donc pas absurde et c'est une pratique assez répandue (voir [thonny](https://github.com/thonny) par exemple). Je propose de nommer ce projet Pydiderot.

L'idée c'est de passer de  dépôts perdus sur le github d'un prof de math à un espace Pydiderot regroupant tout ca. Chaque sous-projet aura toujours son dépôt  et donc ses issues dédiées. La seule différence c'est que les dépôts n'appartiendront plus à @cspaier mais à @Pydiderot ce qui est positif car ça reflète plus la réalité.

A mon avis c'est plus clair et cohérent comme organisation. La paternité des projets est assumée collective et le lien est affiché.  Concrètement ça ne change rien du tout à notre manière de travailler.

> Rien ne nous obligeait à regrouper.

Rien ne nous oblig**e** à regrouper. J'avance des arguments en faveur.

> Mais fais la bascule pendant les vacances stp

Of course! J'ai rien touché avant accord. D’ailleurs @byache à peut-être un avis?

PS: Je vois pas en quoi c'est contraire à la fédération. En terme politique on regroupe des commissions de travail qui ont toujours été liées sous un nom commun qui n'a de pouvoir que symbolique. Les commissions travaillent comme avant. Avant, les réunions avaient lieu dans mon jardin, je propose d'occuper à titre gratis un lieu pour travailler sur l'enseignement de python au secondaire. Je propose le nom de Pydiderot.

**Comment by al-coloic** [comment]
j'aime quand mon troll rolls.

**Comment by cspaier** [comment]
On bascule?

**Comment by byache** [comment]
D'accord. Pas de problème

**Comment by cspaier** [comment]
Here we go!

**Comment by cspaier** [comment]
Du coup j'ai bien envie de créer un nouveau dépot Pydiderot qui explique l'ensemble du projet: Créer des outils pour enseigner et apprendre Python

**Comment by byache** [comment]
Tu veux dire un clone du dépôt qui appartiendrait à pydiderot plutôt qu'à spaier ? Fais à ta guise, franchement pas de problème en ce qui me concerne. On essaye de se mettre à jour pour combler l'immense vide créé par ton départ :-) 
Tu l'utilises dans ton nouveau contexte pro ?

**Comment by byache** [comment]
PS : pour le moment, le vide concernant les clubs ne se voit pas trop grâce au covid !!

**Comment by climu** [comment]
> Tu l'utilises dans ton nouveau contexte pro ?

Je tente. Disons que je suis amené à le présenter à des collègues et j'ai envie que ca fasse propre au premier abord. Que quelqu'un qu'y ne connaisse rien au projet s'y retrouve rapidement. Dans tous les cas ça ne peut pas faire de mal.

Ce que j'ai en tête:
- `pydiderot`: Dépot global ne contenant que de la doc. Explique le projet, et introduit les différents volets.
- `pydiderotlibs`: les bibliothèques
- `pydiderotIDE`: un IDE clef en main
- `pydago`: Documents pour les enseignants.

J'ai envie de faire un dépot global en lisant ces lignes par exemple dans le readme de pydiderotIDE:

> Le projet a démarré en 2018. Il se base sur le programme de mathématiques de Seconde de 2009 et l'enseignement de Python aux élèves de Seconde.
> 
> Depuis la rentrée 2019, les programmes du lycée ont changé, Python y est présent de manière officielle. Nous laissons les professeur-e-s de mathématiques ou des autres matières jugés et enrichir le projet. 

Ca aurait plus sa place dans `pydiderot` que dans la documentation d'un IDE.

> On essaye de se mettre à jour

Hésite pas si je peux aider hein!

**Comment by cspaier** [comment]
Tu l'utilises dans ton nouveau contexte pro ?

Je tente. Disons que je suis amené à le présenter à des collègues et j'ai envie que ca fasse propre au premier abord. Que quelqu'un qu'y ne connaisse rien au projet s'y retrouve rapidement. Dans tous les cas ça ne peut pas faire de mal.

Ce que j'ai en tête:

-   pydiderot: Dépot global ne contenant que de la doc. Explique le projet, et introduit les différents volets.
-   pydiderotlibs: les bibliothèques
-   pydiderotIDE: un IDE clef en main
-   pydago: Documents pour les enseignants.

J'ai envie de faire un dépot global en lisant ces lignes par exemple dans le readme de pydiderotIDE:

    Le projet a démarré en 2018. Il se base sur le programme de mathématiques de Seconde de 2009 et l'enseignement de Python aux élèves de Seconde.

    Depuis la rentrée 2019, les programmes du lycée ont changé, Python y est présent de manière officielle. Nous laissons les professeur-e-s de mathématiques ou des autres matières jugés et enrichir le projet.

Ca aurait plus sa place dans pydiderot que dans la documentation d'un IDE.

    On essaye de se mettre à jour

Hésite pas si je peux aider hein!

**Comment by cspaier** [comment]
Bon, sinon je ferme ca hein.
