### ISSUE TITLE
tentative d'install à la maison

### ISSUE THREAD

**Issue by al-coloic** [cspaier/pydiderotlibs#27]
sous linux 
`maison:~$pip install pydiderotlibs
Collecting pydiderotlibs
  Downloading https://files.pythonhosted.org/packages/7e/ff/a7a7e6d47a0b71a1703863d8dfefbec49e068fc2017afa0f78139545ae87/pydiderotlibs-0.0.14.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-fyjwpn/pydiderotlibs/setup.py", line 15, in <module>
        for line in open(os.path.join(SETUPDIR, 'requirements.txt'), encoding="UTF-8"):
    TypeError: 'encoding' is an invalid keyword argument for this function
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-fyjwpn/pydiderotlibs/
maison:~$ python --version
Python 2.7.17
maison:~$ pip3 install pydiderotlibs
Collecting pydiderotlibs
  Downloading https://files.pythonhosted.org/packages/51/b9/51fed95304120c767d5005b3fd7aae63efc3854c69a050507d4c2b9fb861/pydiderotlibs-0.0.14-py3-none-any.whl
Collecting pygame (from pydiderotlibs)
  Downloading https://files.pythonhosted.org/packages/8e/24/ede6428359f913ed9cd1643dd5533aefeb5a2699cc95bea089de50ead586/pygame-1.9.6-cp36-cp36m-manylinux1_x86_64.whl (11.4MB)
    100% |████████████████████████████████| 11.4MB 126kB/s 
Installing collected packages: pygame, pydiderotlibs
Successfully installed pydiderotlibs-0.0.14 pygame-1.9.6
maison:~$ 
`
Il faut peut-être préciser les versions de python à utiliser dans le manuel d'instalation non ?

**Comment by al-coloic** [comment]
installer, rebouter, thonny sur l'interpreter 3.6.
`from pydiderotlibs import * 
from pydiderotlibs.repere import * `
retourne
'Merci d'utiliser la librairie repere du module pydiderot.

N'hésitez pas à consulter la documentation en ligne:

https://pydiderotlibs.rtfd.io/librairies/repere.html'

**Comment by cspaier** [comment]
Si je comprends bien: Tu as voulu installer pydiderotlibs dans ton environnement python par défaut qui est en version 2.7.17. Ca ne fonctionne pas car il faut du python 3.

Tu as [mis à jour la doc](https://github.com/cspaier/pydiderotlibs/commit/163d7cd817843abcc4590ac06e09c3e692a98206) et l'utilisateur devrait s'en sortir avec l'utilisation de `pip3`.

Pour être propre, il faudrait identifier la version minimum de python nécessaire au fonctionnement de pydiderotlibs et l'indiquer dans la doc.

Sinon, je ne peux que recommander l'utilisation [d’environnements virtuels python](https://docs.python.org/fr/3/library/venv.html) et un coup d’œil [ici](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code-and-syntax-highlighting).

**Comment by al-coloic** [comment]
Alors pour les environnements virtuels : oui mais non. Cela rajoute une épaisseur au millefeuille, certainement optimal pour un dev, plus que discutable pour un user :  a savoir un prof de math qui ne comprend pas grand chose en info.
Proposition le mettre dans la doc comme solution experte.

**Comment by al-coloic** [comment]
Je réouvre car après mise à niveau vers xubuntu 20.04 :
`@maison:~$ sudo pip3 install pydiderotlibs
[sudo] Mot de passe de toto : 
Collecting pydiderotlibs
  Downloading pydiderotlibs-0.0.14-py3-none-any.whl (28 kB)
Collecting pygame
  Downloading pygame-1.9.6.tar.gz (3.2 MB)
     |████████████████████████████████| 3.2 MB 4.2 MB/s 
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-yjhzthc7/pygame/setup.py'"'"'; __file__='"'"'/tmp/pip-install-yjhzthc7/pygame/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-yjhzthc7/pygame/pip-egg-info
         cwd: /tmp/pip-install-yjhzthc7/pygame/
    Complete output (29 lines):
    
    
    WARNING, No "Setup" File Exists, Running "buildconfig/config.py"
    Using UNIX configuration...
    
    /bin/sh: 1: sdl-config: not found
    /bin/sh: 1: sdl-config: not found
    /bin/sh: 1: sdl-config: not found
    Package freetype2 was not found in the pkg-config search path.
    Perhaps you should add the directory containing `freetype2.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'freetype2' found
    Package freetype2 was not found in the pkg-config search path.
    Perhaps you should add the directory containing `freetype2.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'freetype2' found
    Package freetype2 was not found in the pkg-config search path.
    Perhaps you should add the directory containing `freetype2.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'freetype2' found
    /bin/sh: 1: freetype-config: not found
    /bin/sh: 1: freetype-config: not found
    /bin/sh: 1: freetype-config: not found
    
    Hunting dependencies...
    WARNING: "sdl-config" failed!
    WARNING: "pkg-config freetype2" failed!
    WARNING: "freetype-config" failed!
    Unable to run "sdl-config". Please make sure a development version of SDL is installed.
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
`

**Comment by cspaier** [comment]
Arf,
Bon, j'ai pu reproduire sous python 3.8:
```
Collecting pygame
  Downloading pygame-1.9.6.tar.gz (3.2 MB)
     |████████████████████████████████| 3.2 MB 3.5 MB/s 
    ERROR: Command errored out with exit status 1:
     command: /home/cspaier/Pythonprojects/test/3.8/3.8-venv/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-imdccond/pygame/setup.py'"'"'; __file__='"'"'/tmp/pip-install-imdccond/pygame/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-imdccond/pygame/pip-egg-info
         cwd: /tmp/pip-install-imdccond/pygame/
    Complete output (29 lines):
    
    
    WARNING, No "Setup" File Exists, Running "buildconfig/config.py"
    Using UNIX configuration...
    
    /bin/sh: 1: sdl-config: not found
    /bin/sh: 1: sdl-config: not found
    /bin/sh: 1: sdl-config: not found
    Package freetype2 was not found in the pkg-config search path.
    Perhaps you should add the directory containing `freetype2.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'freetype2' found
    Package freetype2 was not found in the pkg-config search path.
    Perhaps you should add the directory containing `freetype2.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'freetype2' found
    Package freetype2 was not found in the pkg-config search path.
    Perhaps you should add the directory containing `freetype2.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'freetype2' found
    /bin/sh: 1: freetype-config: not found
    /bin/sh: 1: freetype-config: not found
    /bin/sh: 1: freetype-config: not found
    
    Hunting dependencies...
    WARNING: "sdl-config" failed!
    WARNING: "pkg-config freetype2" failed!
    WARNING: "freetype-config" failed!
    Unable to run "sdl-config". Please make sure a development version of SDL is installed.
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```
Par contre, pas de problème sous python 3.7. Tu peux donc bosser sous python 3.7 si tu préfères.

Sinon des pistes par [ici](https://stackoverflow.com/questions/19579528/pygame-installation-sdl-config-command-not-found).

Solution bourrine sans se prendre la tête: `sudo apt-get install python-dev libsdl-image1.2-dev libsdl-mixer1.2-dev libsdl-ttf2.0-dev libsdl1.2-dev libsmpeg-dev libportmidi-dev ffmpeg libswscale-dev libavformat-dev libavcodec-dev libfreetype6-dev`

Ou, essayer d'installer une autre version de pygame `python3 -m pip install pygame==2.0.0.dev10`.

Le souci c'est `PyGame-1.9.1 was created in 2009 so it still use old SDL 1.2 not new SDL2.` ce qui me fait référencer #15 .

**Comment by al-coloic** [comment]
Que je comprenne bien le bug
python 3.7 + pygame1.9.1 = ok
python 3.8+pygame 1.9.1= bug
python 3.8+pygame 2.0.0=ok
et tout revient à #15
Je n'ai plus qu'à me faire un environnement de travail sous python 3.7.

**Comment by cspaier** [comment]
Affirmatif!

> Je n'ai plus qu'à me faire un environnement de travail sous python 3.7.

Au cas ou ca gagne du temps à quelqu'un...
Sous debian (*buntu, mint):
`sudo add-apt-repository ppa:deadsnakes/ppa`
`sudo apt update`
`sudo apt install python3.7 python3.7-dev python3.7-venv python3.7-tk`
`python3.7 -m venv venv-3.7`
`source venv-3.7/bin/activate`

Pour le désactiver: `deactivate`

Notons que `venv-3.7` est le nom de ton venv. Tu peux choisir ce que tu veux.
En général je structure comme ca: Un dossier nommé comme ton projet. Dedans deux dossiers: le venv et le projet.
            
EDIT: Ajout de `python3.7-tk`.

**Comment by cspaier** [comment]
On ferme?

**Comment by al-coloic** [comment]
attends 2 sec, je pense mettre ça dans la doc...

**Comment by al-coloic** [comment]
P....... !
si tu bosses avec un venv, en faisant gaffe de mettre le bon interpréteur python dans thonny, la bibliothèque tkinter est importée par :  `import tk`
Alors que dans nos bibliothèques et un environnement par défaut c'est : `import tkinter`
Du coup, comme je bosse avec un petit fichier test.py dans dossier git pydiderotlibs, il faut que je change dans le fichier chaines.py le code pour l'import de Tkinter.
c'est incroyable ! Faut vraiment qu'on s'en débarasse.

**Comment by cspaier** [comment]
Hum t'es sur?
Je trouve cela nul part. C'est quoi tes erreurs?

**Comment by al-coloic** [comment]
`ModuleNotFoundError: No module named 'tkinter'`

Si je mets `tk` cela fonctionne

**Comment by cspaier** [comment]
Tente: `sudo apt install python3.7-tk`

**Comment by al-coloic** [comment]
ça fonctionne. J'avais fait `sudo apt python-tkinter` avec l'environnement 3.7 activé mais faut croire que cela n'a pas suffit. cimer

**Comment by cspaier** [comment]
De rien. En fait le venv activé n'aura d'impact que sur les applications python. `apt` s'en fout complètement. Il va simplement installer le paquet demandé soit, dans ton exemple, `tkinter` pour la version par défaut de python (3.8 on dirait). 

Du coup c'est un oubli de ma part dans ce [post](https://github.com/cspaier/pydiderotlibs/issues/27#issuecomment-708504126). Changer:
`sudo apt install python3.7 python3.7-dev python3.7-venv` et `sudo apt install python3.7 python3.7-dev python3.7-venv python3.7-tk`.

**Comment by cspaier** [comment]
Je ferme hein. 
Dépuis [09dbc81](https://github.com/cspaier/pydiderotlibs/commit/09dbc8155e0bbbf1bdf4058defc8c2788295958c) on est passé à pygame 2.0.
