### ISSUE TITLE
MAJ de la doc

### ISSUE THREAD

**Issue by al-coloic** [cspaier/pydiderotlibs#28]
Après la migration des libs de pydiderot vers pydiderotlibs, j'essaye de mettre la doc à jour.
Mais je ne pige pas encore tout.

Par exemple : à cette adresse [de la doc pour participer sur le dépôt pydiderotlibs](https://pydiderotlibs.readthedocs.io/contributing.html) il est écrit que Sphynx compile la doc à partir de [https://github.com/cspaier/pydiderot/tree/dev/docs](https://github.com/cspaier/pydiderot/tree/dev/docs). doc si je comprends sur la branche dev de pydiderot.

Il faudrait plutôt aller documenter la doc de pydiderotlibs. Mais si je ne me trompe pas il n'y a qu'une branche master sur github.
donc l'adresse ne devrait-elle pas être [https://github.com/cspaier/pydiderotlibs/tree/master/docs](https://github.com/cspaier/pydiderotlibs/tree/master/docs) ?

**Comment by al-coloic** [comment]
faire maj des liens de 

- [x] [/docs/compiler_la_documentation.md](/pydiderotlibs/docs/compiler_la_documentation.md)
- [x]  [/CONTRIBUTING.md ](/pydiderotlibs/CONTRIBUTING.md )

> Nous acceptons les Pull requests dans la branche dev. 

y a une branche dev dans pydiderotlibs de prévue ?

**Comment by cspaier** [comment]
Bien vu!

La documentation de pydiderotlibs est crée à partir de pydiderotlibs. En aucun cas de pydiderot. Il faut mettre à jour les liens comme tu l'as compris.

Ce qui c'est passé: La doc a été écrite pour pydiderot. J'ai copié/collé pour pydiderotlibs en mettant à jour le plus possible. Clairement j'en ai loupé.

> y a une branche dev dans pydiderotlibs de prévue ?

C'est pas au programe. On pourrait avoir un branche dev sur laquelle on bosse et une branche master qui correspondrait à ce qui est publié sur [pypi](https://pypi.org/project/pydiderotlibs/) mais à mon avis ce n'est pas nécessaire. On a pypi qui permet de publier les versions proprement et ce github est l'espace de travail.

**Comment by al-coloic** [comment]
dans [/CONTRIBUTING.md](/CONTRIBUTING.md), maj :

> Il n'y à ce jour qu'une branche github créée et maintenue. Nous acceptons les Pull sur cette branche.

Les Pushet commits sont-ils modérés sur cette branche ? Sinon est-e bien raisonnable que quiconque push sur la branche ?

**Comment by cspaier** [comment]
Seuls les collaborateurs (Paul, toi, moi) peuvent participer directement sur ce dépot. Les autres utilisateurs souhaitant participer devront soumettre une pull request (voici [un exemple](https://github.com/thonny/thonny/pull/736) de PR). On pourra alors relire la PR, en discuter, demander des modifications, et enfin l'incorporer dans notre dépot.

**Comment by al-coloic** [comment]
da !
