### ISSUE TITLE
Captures d'écran dans la doc

### ISSUE THREAD

**Issue by cspaier** [cspaier/pydiderotlibs#29]
Ca serait pas mal je pense.

Pour `entree`, `repere` et `graphique`. Pour graphique on peut même mettre un gif!

**Comment by al-coloic** [comment]
mis un fichier /docs/source/_static/demander_entier.png comme capture et rajouter la ligne
`.. figure:: /docs/source/_static/demander_entier.png :align: center`
dans /docs/librairies/entree.md mais cela n'affiche rien dans readthedocs ?

**Comment by cspaier** [comment]
Merci!

Je regarde quand j'ai le temps. Mais si tu bosses sur la doc, je conseille fortement la [compilation en local](https://pydiderotlibs.readthedocs.io/compiler_la_documentation.html).

**Comment by al-coloic** [comment]
compiler en local sous windows au bahut ? J'en parle à mon référent numérique. :+1:

**Comment by al-coloic** [comment]
bon ça fonctionne, l'image est là

**Comment by cspaier** [comment]
Par contre, je suis pour mettre des images dans `repere` et `graphique`.
Je réouvre donc.
