### ISSUE TITLE
Deploiement au lycée pip?

### ISSUE THREAD

**Issue by cspaier** [cspaier/pydiderotlibs#3]
Bon maintenant on install thonny avec pip. Je pensai donc publier nos libs sur pypi pour les installer avec pip.

Mais... l'inconvénient de cette méthode est que installer ou mettre à jour les libs nécessitera de passer physiquement sur chaque poste. Pas fun.

De plus les imports seront un peu plus compliqué pour les élèves: `from pydiderotlibs.lycee import *`

Je pense donc mettre nos libs dans un dossier partagé en lecture au lycée et configurer `PYTHONPATH` pour qu'il lise ce dossier.

**Comment by cspaier** [comment]
Pour les imports on peut simplifier en utilisant [ca](https://packaging.python.org/guides/packaging-namespace-packages/).

Ca va compliquer un peu la structure du dossier mais en échange, on pourra faire: `from pydiderotlibs import lycee`.

Le problème du déploiement reste présent.

**Comment by byache** [comment]
Du coup, ce sera ok pour une MaJ rapide la semaine de la rentrée, ou il risque d'y avoir des pbs ?

**Comment by cspaier** [comment]
Ca devrait pas poser de problème.

**Comment by cspaier** [comment]
On va installer [ce plugin](https://github.com/cspaier/thonny-pydiderot-plugin) thonny.

Comme ca on pourra faire des maj nous même.

**Comment by cspaier** [comment]
Une question quand même:

On peut insérer nos libs de deux manières:

1. directement: `from graphique import *`
2. dans pydiderotlibs: `from pydiderotlibs.graphique import *`

Le 1. est plus simple mais le 2. est cohérent avec une installation par pip.

Avis?

**Comment by al-coloic** [comment]
j'ai l'impression qu'on se pose la même question dans plusieurs fils !
/cspaier/pydiderot#34
/cspaier/pydiderotlibs#3
/cspaier/pydiderotlibs#23

**Comment by cspaier** [comment]
Hum ... c'est le bazar dans nos issues oui.

Ici on se demandait en principe comment déployer au lycée Diderot. Je sais pas ou vous en êtes mais l'année dernière, on mettait pydiderotlibs dans un dossier partagé et on installait thonny et [thonny-pydiderot-plugin](https://github.com/cspaier/thonny-pydiderot-plugin). Ca fonctionnait bien et ca permettait de changer facilement les librairies en cas de mise à jour.

Si ca tourne toujours de la même manière, on peut fermer cette issue, quitte à ré ouvrir en cas de changement.

**Comment by al-coloic** [comment]
avant de fermer, peut-on décider où mettre la procédure de déploiement au lycée ?
Il me semble qu'on devrait la mettre comme exemple pour d'autres sur github et nous, profs actuels de diderot, la mettre sur atrium.

**Comment by cspaier** [comment]
Un bon vieux fichier `deploiement.md` dans `docs` ?

**Comment by al-coloic** [comment]
oui !

mais dans pydiderot/docs pas les librairies

**Comment by al-coloic** [comment]
up

**Comment by al-coloic** [comment]
bon en fait je ferme ici et réouvre sur pydiderot [là](https://github.com/cspaier/pydiderot/issues/37)
