### ISSUE TITLE
fonction repeat pas dans la doc

### ISSUE THREAD

**Issue by byache** [cspaier/pydiderotlibs#31]
J'avais mis dans "lycee" une fonction repeat(f,n) qui n'est apparemment pas butinée par la documentation.
A voir comment fonctionne le butinage (il doit y avoir un truc à ajouter ou alors il faut que je mette cette fonction ailleurs...

**Comment by cspaier** [comment]
Etrange.
On lit dans [docs/librairies/lycee.md](https://github.com/cspaier/pydiderotlibs/blob/master/docs/librairies/lycee.md): 
```
## Documentation
.. automodule:: pydiderotlibs.math_lycee
    :members:
    :member-order: bysource
```
J'ai vérifié et la doc compile bien chez readthedocs: [![Documentation Status](https://readthedocs.org/projects/pydiderotlibs/badge/?version=latest)](https://pydiderot.readthedocs.io/projects/pydiderotlibs/?badge=latest). A [tester en local](https://pydiderotlibs.readthedocs.io/compiler_la_documentation.html).

Pour reférence:
https://github.com/cspaier/pydiderotlibs/blob/d2a48713d8f52e55e525cea517370b6bdae13b05/pydiderotlibs/math_lycee.py#L31-L38


Comment on butine? [sphinx autodoc](https://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html) avec l'extension [napoléon](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/).

**Comment by cspaier** [comment]
C'est reglé. Je sais pas ce que tu as fait @byache .
Hésite pas à indiquer le commit qui résout les issues ;)

**Comment by byache** [comment]
Ah, OK. Mais je ne pensais pas avoir règle quoi que ce soit.
J'ai juste changé un saut de ligne dans un commentaire mais ça n'a pas du faire gd chose. J'ai aussi ajouté une fonction.
Peut être que le fait de modifier le fichier à relancé le burinage...

**Comment by cspaier** [comment]
> J'ai juste changé un saut de ligne dans un commentaire mais ça n'a pas du faire gd chose. 

Sisi, ca peut suffire.

> Peut être que le fait de modifier le fichier à relancé le burinage...

La doc est compilée à chaque commit. 

Franchement pour la doc, il faut compiler en local. Sinon c'est comme écrire du latex en attendant 5 minutes la compilation. Sans compter que ca oblige à pousser sur github touts les commits de test.
