### ISSUE TITLE
new release ?

### ISSUE THREAD

**Issue by byache** [cspaier/pydiderotlibs#34]
Je ferais bien une nouvelle release de pydiderotlibs vers Pypi pour voir comment ça marche et pour voir aussi comment marche la mise à jour de la version installée au lycée...
Des objections ?

**Comment by cspaier** [comment]
Bonne idée. Ya eu du boulot de fait en plus. T'as lu [ça](https://github.com/cspaier/pydiderotlibs/blob/master/docs/maj_pypi.md)?

Au lycée, je sais plus trop comment ça marche. Dossier partagé ou demande à Denis de `pip install pydiderotlibs --upgrade` ?

**Comment by byache** [comment]
Oui, justement. J'ai lu ta doc sur Pypi et wheel :  merci, d'ailleurs pour toutes ces aides !

**Comment by cspaier** [comment]
>  merci, d'ailleurs pour toutes ces aides !

De rien. Je les fait pour moi en premier lieu afin de ne pas avoir à chercher à chaque fois.

**Comment by cspaier** [comment]
@byache la version 0.016 a un bug sérieux dans liste corrigé dans [ce commit](https://github.com/Pydiderot/pydiderotlibs/commit/da2162ba124d0dac8687488082e16f6c68b38012).
Du coup je vais maj aujourd'hui.

**Comment by cspaier** [comment]
Fait. Tu feras la prochaine.
