### ISSUE TITLE
Euclide étendu ?

### ISSUE THREAD

**Issue by JordanEmme** [cspaier/pydiderotlibs#36]
Le module arithmétique comporte trois fonctions : pgcd, quotient et reste.

Au risque de passer pour un vieux c\*n, de mon temps, au lycée, on apprenait à remonter l'algorithme d'Euclide pour trouver une relation de Bézout. Blague à part, je ne sais pas si c'est toujours d'actualité.

Du coup j'ai deux questions.

1. Est-ce que la relation de Bézout et l'algorithme de remonté d'Euclide pour trouver un couple (u,v) pour la relation sont toujours enseignés ?
2. Dans l'affirmative, est-ce qu'ajouter cet algorithme vous serait utile ? Je peux m'en occuper.

Sinon, pour ce genre de maths, l'exponentiation rapide modulaire est utile, surtout si vous voulez faire RSA ou des trucs du genre. Je ne sais pas si ça peut vous être utile pour votre enseignement ou non, mais, encore une fois, dans le cas où ça peut aider quelqu'un, je peux implémenter ça avec plaisir.

**Comment by byache** [comment]
Bonjour,
Je précise que je n'ai pas enseigné en terminale depuis les [nouveaux programmes](https://eduscol.education.fr/1723/programmes-et-ressources-en-mathematiques-voie-gt).
Dans les programmes, je vois seulement ce genre de truc (Euclide, Bezout, RSA) en maths expertes.
Donc c'est à mon sens peu utile d'implémenter ces algorithmes. Mais en même temps cela peut quand même s'avérer précieux de trouver les choses toutes prêtes, pour un enseignant de maths experte (ou peut-être de NSI -le nom barbare pour dire "informatique" dans l'éducation nationale-) qui aurait envie de faire RSA ?

**Comment by al-coloic** [comment]
Salut jordan,

un peu le même réponse que byache : mon objectif est essentiellement pour enseigner aux secondes et premières. Après on rentre dans le dur. Mais comme je ne suis pas (encore) sur les maths expertes, je n'en aurais pas l'usage.

Mais si tu en vois l'usage, ou juste envie de te faire plaisir, vas y

**Comment by cspaier** [comment]
Perso j'enseigne en math expertes  cette année.
Pour info le BO est dispo [ici](https://cache.media.eduscol.education.fr/file/SPE8_MENJ_25_7_2019/82/5/spe264_annexe_1158825.pdf) et on y lit:

![image](https://user-images.githubusercontent.com/44053087/103300864-3552b400-4a00-11eb-968d-72eaf5614f93.png)

Du coup:

> Est-ce que la relation de Bézout et l'algorithme de remonté d'Euclide pour trouver un couple (u,v) pour la relation sont toujours enseignés 

Oui.

> Dans l'affirmative, est-ce qu'ajouter cet algorithme vous serait utile ? Je peux m'en occuper.

Oui. Merci!

C'est clairement au programme et a donc sa place dans pydiderotlibs.
