### ISSUE TITLE
droits et prog travail

### ISSUE THREAD

**Issue by byache** [cspaier/pydiderotlibs#4]
Salut Clément,
J'ai cloné le dépôt mais je veux bien avoir des droits pour pouvoir faire des pushs ;-)

Ce que je pensais faire, c'est faire du ménage dans "lycee.py" et "repere.py" : essentiellement faire en sorte que les noms des fonctions soient plus cohérents les uns avec les autres.

Ensuite, peut-être faire une bibliothèque nouvelle pour les SNT (sciences du numérique et technologie)

**Comment by cspaier** [comment]
Salut Paul.

C'est fait!

Des bonnes idées.

**Comment by byache** [comment]
Voici quelques propositions de modifications.
J'attend un peu pour voir s'il y a des oppositions avant de les faire.

- clarifier les noms des librairies :
"lycee" deviendrait "math_lycee"
"repere" deviendrait "graphique_statique"
"graphique" deviendrait "graphique_dynamique"

- homogénéiser les noms des fonctions : 
perso, je ne me souviens jamais du nom des fonctions : certaines commencent pas "trace" et d'autres par "creer".  Je propose d'enlever tous les "trace" et les "creer". Il y a par ailleurs "affiche_fenetre()" qui dans le code paraît nécessaire mais si on ne l'utilise pas, tout marche quand même... Du coup, cette fonction resterait inchangée mais on peut continuer à ne pas l'utiliser... ?
"creer_fenetre" devient "fenetre"
"trace_point" devient "point"
etc.

- homogénéiser l'ordre des variables : 
on met de partout : 1) variables de coordonnées 2) couleur 3) variables de taille 4) le reste si nécessaire
Pour point, cela reste donc : "point(x,y,couleur,taille,forme)"
Il y a peu de modif à faire car la plupart du temps cet ordre des variables est déjà respecté. Mais il faut faire une vérification systématique.

- homogénéiser les deux fonctions "rectangle" (des modules de graphique statique et dynamique).
Dans une des fonctions il faut donner les coord de deux coins diagonalement opposés et dans l'autre, la largeur et la hauteur.
Je propose de mettre dans les deux cas : 
"rectangle(xcentre, ycentre, couleur, largeur, hauteur, remplissage éventuel)

- créer des alias avec les noms en anglais. Je comprend que les mots en français peuvent simplifier les choses pour les élèves. Mais tout python est en anglais et du coup, on ne sait plus forcément quand il faut mettre de l'anglais et quand il faut mettre du français (mais avec des fautes puisqu'il ne faut pas mettre d'accents ;-)
Donc on avait évoqué l'idée de permettre les deux langues dans les fonctions créées par nous.
Il y a plein de cas comme "point" ou "rectangle" où la question est vite résolue. Pour les autres, il faut créer un alias. Exemple : créer la fonction "circle" qui exécute en réalité l fonction "cercle" (ou le contraire).

**Comment by byache** [comment]
On avait évoqué le fait de créer une fonction "repeat(f,n)" qui exécute n fois la fonction f.
Ainsi, l'enseignement de l'algo pourrait suivre la progression : 
notion de fonction (en python) --> notion de boucle (sans utiliser de variable, grâce à repeat(f,n))
--> notion de variable (progressivement et en parallèle des deux points précédents)
--> boucle avec variable (soit while, soit for...)

**Comment by byache** [comment]
On avait encore donné d'autres idées que je n'ai plus trop en tête... Peut-être que Denis ou Loïc par exemple auront des souvenirs...

**Comment by cspaier** [comment]
Merci pour le boulot Paul.

Comme ca c'est un peu dur de suivre ce qui est fait et a faire. Je suggère de créer une issue par tache. Comme ca on la ferme au moment venu.

J'ai référencé les comitts et j'ai l'impression que tu as finis cette [liste](https://github.com/cspaier/pydiderotlibs/issues/4#issuecomment-523347052).

Je propose donc de fermer ici et de créer une issue pour la fonction "repeat(f,n)".
