### ISSUE TITLE
Probleme dans la recuperation des touches pressees

### ISSUE THREAD

**Issue by Quelqu2** [cspaier/pydiderotlibs#40]
Les touches pressees ne sont pas recuperees.

**Comment by cspaier** [comment]
Merci pour le retour.
Je confirme avec python 3.8.10 et pydiderotlibs 0.0.22.
C'est un bug. On regarde les solutions dans #41

**Comment by cspaier** [comment]
Pour information, la gestion de la souris fonctionne.

**Comment by cspaier** [comment]
Bon, c'est moche.
Avant `pygame 2.0`, `pygame.get_pressed()` retournait une liste de valeurs `0/1` dont l'index correspondait à `pygame.key.name(index)` pour avoir une version lisible de la touche.

Depuis `pygame 2.0`, `pygame.get_pressed()` retourne une instance de `pygame.ScanCodeWrapper`. Quand on parcourt cela avec `for` l'insance est changée en `list` et on perd l'index.

On peut tester les touches une par une:
```python
touches = pygame.key.get_pressed()
if touches[pygame.K_a]: print('la touche a est enfoncée').
```
La meilleur doc que j'ai trouvé sur le problème vient de [reddit](https://www.reddit.com/r/pygame/comments/gfc13v/pygamekeyget_pressed_in_pygame_2/), c'est dire :(

Et la (délicieuse) [doc pygame](https://www.pygame.org/docs/ref/key.html#pygame.key.get_pressed) mentionne:

> There is also no way to translate these pushed keys into a fully translated character value

Le problème c'est qu'on veut choper toutes les touches. Deux idées:
1. une fonction `check_touche(touche:str)` qui vérifie si la touche `"a"` est enfoncée:
```python
def check_touche(touche:str):
    touches = pygame.key.get_pressed()
    return touches[pygame.key.key_code(touche)]
```
A voir si l'appel répété de `pygame.key.get_pressed()` ralentit. Si oui, on stoque `touches` dans une globale avec `demande_evenements`.

2. Garder le fonctionnement courant. Je crains qu'il faille stoquer toutes les touches pygame `(pygame.K_a, pygame.K_b,...)` quelquepart et boucler la dessus.

**Comment by barnabehvrd** [comment]
La doc précise aussi:
> See the pygame.KEYDOWN events on the [pygame.eventpygame module for interacting with events and queues](https://www.pygame.org/docs/ref/event.html#module-pygame.event) queue for this functionality.

Peut-être qu'écouter directement l’évent pourrait également permettre de récupérer les touches

![image](https://user-images.githubusercontent.com/40314287/190642059-023e935a-3bdb-40cd-b3ae-0a91742d7c4f.png)


Je connais mal/pas la doc de pygame donc je ne suis pas sûr de ce que je raconte, mais c'est peut-être une solution

**Comment by barnabehvrd** [comment]
Si besoin, il y a aussi la possibilité de regarder ici pour avoir des jolis exemple de code utilisant `pygame.key.get_pressed()`: 

https://github.com/search?l=Python&o=desc&q=pygame.key.get_pressed&s=indexed&type=Code

**Comment by cspaier** [comment]
> Peut-être qu'écouter directement l’évent pourrait également permettre de récupérer les touches

Le problème c'est que `pygame.KEYDOWN ne gère pas plusieurs touchent appuyées en même temps. Ca génère une queue d'évenements. Pour une entrée clavier de type texte c'est ok. Mais pour un jeux c'est moyen. Marrant pour un truc qui s'appelle pygame, non? Voir #21 et #15 .


> Si besoin, il y a aussi la possibilité de regarder ici pour avoir des jolis exemple de code utilisant pygame.key.get_pressed():

Merci. A y regarder rapidement, je n'y voit que des utilisations du type `if touches[pygame.K_a]`.

Je vais faire un truc ~~sale~~ rapidement ce soir parceque les jeunes bossent dessus demain.

**Comment by cspaier** [comment]
bon...
```
K_BACKSPACE   \b      backspace
K_TAB         \t      tab
K_CLEAR               clear
K_RETURN      \r      return
K_PAUSE               pause
K_ESCAPE      ^[      escape
K_SPACE               space
K_EXCLAIM     !       exclaim
K_QUOTEDBL    "       quotedbl
K_HASH        #       hash
K_DOLLAR      $       dollar
K_AMPERSAND   &       ampersand
K_QUOTE               quote
K_LEFTPAREN   (       left parenthesis
K_RIGHTPAREN  )       right parenthesis
K_ASTERISK    *       asterisk
K_PLUS        +       plus sign
K_COMMA       ,       comma
K_MINUS       -       minus sign
K_PERIOD      .       period
K_SLASH       /       forward slash
K_0           0       0
K_1           1       1
K_2           2       2
K_3           3       3
K_4           4       4
K_5           5       5
K_6           6       6
K_7           7       7
K_8           8       8
K_9           9       9
K_COLON       :       colon
K_SEMICOLON   ;       semicolon
K_LESS        <       less-than sign
K_EQUALS      =       equals sign
K_GREATER     >       greater-than sign
K_QUESTION    ?       question mark
K_AT          @       at
K_LEFTBRACKET [       left bracket
K_BACKSLASH   \       backslash
K_RIGHTBRACKET ]      right bracket
K_CARET       ^       caret
K_UNDERSCORE  _       underscore
K_BACKQUOTE   `       grave
K_a           a       a
K_b           b       b
K_c           c       c
K_d           d       d
K_e           e       e
K_f           f       f
K_g           g       g
K_h           h       h
K_i           i       i
K_j           j       j
K_k           k       k
K_l           l       l
K_m           m       m
K_n           n       n
K_o           o       o
K_p           p       p
K_q           q       q
K_r           r       r
K_s           s       s
K_t           t       t
K_u           u       u
K_v           v       v
K_w           w       w
K_x           x       x
K_y           y       y
K_z           z       z
K_DELETE              delete
K_KP0                 keypad 0
K_KP1                 keypad 1
K_KP2                 keypad 2
K_KP3                 keypad 3
K_KP4                 keypad 4
K_KP5                 keypad 5
K_KP6                 keypad 6
K_KP7                 keypad 7
K_KP8                 keypad 8
K_KP9                 keypad 9
K_KP_PERIOD   .       keypad period
K_KP_DIVIDE   /       keypad divide
K_KP_MULTIPLY *       keypad multiply
K_KP_MINUS    -       keypad minus
K_KP_PLUS     +       keypad plus
K_KP_ENTER    \r      keypad enter
K_KP_EQUALS   =       keypad equals
K_UP                  up arrow
K_DOWN                down arrow
K_RIGHT               right arrow
K_LEFT                left arrow
K_INSERT              insert
K_HOME                home
K_END                 end
K_PAGEUP              page up
K_PAGEDOWN            page down
K_F1                  F1
K_F2                  F2
K_F3                  F3
K_F4                  F4
K_F5                  F5
K_F6                  F6
K_F7                  F7
K_F8                  F8
K_F9                  F9
K_F10                 F10
K_F11                 F11
K_F12                 F12
K_F13                 F13
K_F14                 F14
K_F15                 F15
K_NUMLOCK             numlock
K_CAPSLOCK            capslock
K_SCROLLOCK           scrollock
K_RSHIFT              right shift
K_LSHIFT              left shift
K_RCTRL               right control
K_LCTRL               left control
K_RALT                right alt
K_LALT                left alt
K_RMETA               right meta
K_LMETA               left meta
K_LSUPER              left Windows key
K_RSUPER              right Windows key
K_MODE                mode shift
K_HELP                help
K_PRINT               print screen
K_SYSREQ              sysrq
K_BREAK               break
K_MENU                menu
K_POWER               power
K_EURO                Euro
K_AC_BACK             Android back button
```
un peu de travail absurde et 
```python
keys = []
with open('pygame_keys.txt','r') as f:
    for line in f:
        keys.append(line.split(None, 1)[0])
keys_dict = {}
for key in keys:
    a = input(key +':')
    keys_dict[a] = key
    print("{" + "\n".join("{!r}: {!r},".format(k, v) for k, v in keys_dict.items()) + "}")
```
donnent
```python
    touches = pygame.key.get_pressed()
    for touche, k_touche in TOUCHES_PYGAMES.items():
        if touches[getattr(pygame, k_touche)]:
            evenements[touche] = None
```

**Comment by cspaier** [comment]
On est sur pypi.
Au passage notons la retrocompatibilité! Aucune maj de la doc et les nombreux utilisateurs n'ont pas à modifier leurs scripts.
