### ISSUE TITLE
Docs et alias

### ISSUE THREAD

**Issue by cspaier** [cspaier/pydiderotlibs#5]
Grace à Paul, on a récemment introduit des alias des fonctions et des modules.

J'ai deux questions concernant la doc.

### 1 Alias des fonctions

Je trouve que cela alourdi la doc d'avoir des duplicatas de fonctions (voir [ici](https://pydiderotlibs.readthedocs.io/en/latest/librairies/graphique.html#module-graphique_dynamique) par exemple). Perso quand je lis la doc d'une librairie, je souhaite avoir rapidement un aperçu des fonctions disponibles.

Je propose de choisir systématiquement un nom de fonction "canonique", d'indiquer dans son docstring les alias disponibles, et de supprimer les alias de la doc.

Un truc du genre:

```
point(x, y, couleur=’bleu’)
---------------------------------
Trace un point dans la fenetre graphique.

Alias disponibles: trace_point()

Parameters:  
x (int) – Abscisse du point 
y (int) – Ordonnée du point
couleur (couleur, optionnel) – Couleur du point (bleu par défaut)
```
Je suis pas certain là-dessus.

### 1 Alias des modules
Dans la doc on a toujours `repere` et `graphique`. C'est ma préférence personnelle car je trouve que c'est simple et parlant. 

Par contre les fichiers contenant le code sont `graphique_statique` et `graphique_dynamique`.

- On garde `graphique` et `repere` dans la doc?
- Si oui, je suggère de passer le code dans les fichiers en questions.

Pour info, j'ai deux élèves qui codent le lundi midi en utilisant pydiderotlibs et la doc en ligne. C'est donc pertinent d'avoir une doc de qualité et a jour. Mais bon, c'est le cas sur tout projet et c'est pas nouveau :)

**Comment by byache** [comment]
Salut Clément,
Je suis ok avec tes propositions.

**Comment by cspaier** [comment]
pour le point 1: Concretement, le plus simple pour exclure des fonctions de  la doc c'est d'enlever les docstrings. Je pense que ca va pour des alias.

**Comment by byache** [comment]
Voilà, c'est fait pour les alias dans la doc. Je te laisse remettre le code là où tu le veux, clément ?

**Comment by cspaier** [comment]
Wow, merci Paul.

Oui, je remets le code dans les fichiers, relis et mets à jour sur pypi ce week end.

**Comment by cspaier** [comment]
J'ai mis le code dans `repere` et `graphique`.

Il reste le module `lycee` qui est dans `math_lycee`. Je voulais vérifier pour celui la car j'avais souvenir d'un possible conflit avec le module `lycee` de nos amis d'Amiens.

Pas certain parceque de toute facon on utilise `from pydiderotlibs.lycee`.
