### ISSUE TITLE
repeat(f,n)

### ISSUE THREAD

**Issue by byache** [cspaier/pydiderotlibs#6]
Le code suivant permet de répéter n fois une fonction f, sans qu'on ait besoin d'utiliser la syntaxe des boucles "for" ou "while". Elle correspond donc au naïf "répéter ... fois" qu'on trouve dans les systèmes de programmation par blocs.

```
def repeat(f,n):
    for i in range(n):
        f()
```

### limitations : 
- f doit être une fonction sans variable

- on peut utiliser des variables dans f, mais il faut alors les déclarer comme global à l'intérieur de f et les initialiser à l'extérieur de f. Exemple : 
```
m=0

def f():
    global m
    m=m+1


def repeat(f,n):
    for i in range(n):
        f()
        
repeat(f,3)
print(m)
```
### motivations
A mon avis, cela peut rendre des services, notamment pour enseigner de la façon suivante :
- utilisation en mode console
- notion de fonction
- mise en évidence du fait qu'une structure en boucle du type "répéter" permet de résoudre beaucoup de problèmes
- notion de boucle naïve "répéter n fois"
- utilisation de variables
- boucle for ou while car la boucle naïve est peu pratique

**Comment by cspaier** [comment]
Au top!

On doit pouvoir passer des arguments:
```
def repeat(f,n, args*, kwargs*):
    for i in range(n):
        f(args*, kwargs*)
```

J'ai pas testé ni vérifié la doc mais on doit pouvoir faire un truc comme ca.
Je peux regarder ca pendant les vacances.

On peut aussi balancer comme ca dans `lycee` si ya besoin et mettre à jour plus tard.

**Comment by byache** [comment]
A mon avis, ce n'est pas très utile d'être raffiné car cette fonction est destinée à être rapidement abandonnée : j'imagine une utilisation pendant au maximum le premier trimestre de seconde.
Donc pour le moment, balancer comme ça dans lycee.
Par la suite, pourquoi pas mettre des variables optionnelles (perso je maîtrise mal l'opérateur splat : il faudrait tester pour être sûr de la syntaxe).

**Comment by byache** [comment]
J'ai mis la fonction repeat() (avec l'alias repeter()) dans le code, dans la librairie "math_lycee" (si on crée d'autres fonctions sur les boucles, on fera à l'occasion une librairie dédiée mais pour le moment, je crois que repeat est la seule à ce sujet).
