### ISSUE TITLE
axe des ordonnées

### ISSUE THREAD

**Issue by byache** [cspaier/pydiderotlibs#7]
Perso, j'avais l'habitude d'orienter l'axe des ordonnées vers le haut, comme en maths (mais pas comme en informatique).
Les fonctions préparées pour le moment sont faites avec un axe des ordonnées vers le bas.
Pour apporter de la souplesse sans modifier les utilisations déjà possibles, je propose de créer une variable globale booléenne "axeMath".
Par défaut à "False", mais qu'on peut mettre à "True".
Ensuite, je reprend le code des fonctions graphiques pour que si axeMath=True, l'ordonnée "y" sera remplacée par "Ymax-y", de façon à orienter l'axe à l'envers du sens des informaticiens.
Des avis là dessus ?

**Comment by cspaier** [comment]
Ca peut clairement être utile.

L'approche booléen globale va fonctionner mais n'est pas forcément recommendée.

Il peut être plus propre de créer une sous-class de `pygame.Surface` dont on stoquera une instance dans la variable globale `fenetre`.
Un truc du genre (pas testé):

```python
class Fenetre(pygame.Surface):

    def __init__(self, axeMath=False):
        pygame.Surface.__init__(self)
        self.axeMath=axeMath
    
    def coord_y(self,y):
        if self.axeMath:
            ymax = self.get_surface().get_size()[1]
            return ymax-y
        else:
            return y
```

Comme ca il suffira d'appeller ` fenetre.coord_y(y)` partout.

Bon une variable globale ca fonctionne aussi.

**Comment by byache** [comment]
Oui, c'est vrai que comme ça c'est plus propre au niveau code, mais c'est bizarre à expliquer aux élèves...
Avec une variable globale, coder un cercle qui se déplace verticalement de bas en haut se fait à peu près ainsi : 
`axeMath=True
afficher_fenetre()
x=50
y=0
while True : 
   y=y+1
   circle(x,y,10,"red")`

Si j'ai bien compris ton idée, il faudrait écrire (sans la variable globale) : 
`afficher_fenetre()
x=50
y=0
while True : 
   y=y+1
   circle(x,fenetre.coord_y(y,True),10,"red")`

La dernière ligne me pose problème (pédagogiquement).

**Comment by cspaier** [comment]
Il y a malentendu.

Je suggère seulement de stocker `axeMath` comme attribut de l'object `fenetre` plutôt que comme variable globale.

Je pense que dans tous les cas il faut que `axeMath` soit initialisée dans la fonction `fenetre`. 

On passerait de `fenetre(largeur=200, hauteur=300, titre=’Fenetre graphique’)` à `fenetre(largeur=200, hauteur=300, titre=’Fenetre graphique’, axeMath=False)`.

Ensuite la conversion se ferait dans les fonctions du module.

Dans tous les cas on aura une fonction ou méthode qui sera utilisée dans nos fonctions et pas par les élèves:
```python
def coord_y(y):
        if axeMath:
            ymax = self.get_surface().get_size()[1]
            return ymax-y
        else:
            return y
```

Ça rend l'utilisation par les élèves simple:
```python
fenetre(axeMath=True)
x=50
y=0
while True :
    y=y+1
    circle(x, y, 10, "rouge")
```
La question soulevée "variable globale ou attribut" est ensuite une histoire de style qui n'aura aucune incidence sur l'utilisation élève.

**Comment by cspaier** [comment]
Bon j'ai regardé et c'est bien galère de sous-classer `pygame.surface`. Une variable globale fera l'affaire.
